[package]
name = "oss-rust-sdk"
version = "0.1.0"
authors = ["farmerx"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.10", features = ["blocking"] }
thiserror = "1.0"